/* Generated By:JJTree: Do not edit this line. AstCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wdl.parser;

public class AstCommand extends SimpleNode
{
    String command;

    public AstCommand(int id)
    {
        super(id);
    }

    public AstCommand(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "command";
    }

    public void setCommand(String text)
    {
        this.command = text;
    }

    public String getCommand()
    {
        return this.command;
    }

}
/* JavaCC - OriginalChecksum=773fd0e56fa9fc4b1287d0adefebfb21 (do not edit this line) */
