/* Generated By:JJTree: Do not edit this line. AstCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wdl.parser;

public class AstCall extends SimpleNode
{
    public AstCall(int id)
    {
        super(id);
    }

    public AstCall(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "call";
    }

}
/* JavaCC - OriginalChecksum=8aed95407f67db839f2014bd8a84629b (do not edit this line) */
