/* Generated By:JJTree: Do not edit this line. AstTask.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.wdl.parser;

public class AstTask extends AstScope
{
    private String name;

    public AstTask(int id)
    {
        super(id);
    }

    public AstTask(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "task";
    }

    public String getName()
    {
        return name;
    }

}
/* JavaCC - OriginalChecksum=c7f77334a3b2603c0e8c8a585e357b09 (do not edit this line) */
