/* Generated By:JJTree&JavaCC: Do not edit this line. WDLParserConstants.java */
package com.wdl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int ML_EOL = 4;
  /** RegularExpression Id. */
  int TASK = 6;
  /** RegularExpression Id. */
  int WORKFLOW = 7;
  /** RegularExpression Id. */
  int VERSION = 8;
  /** RegularExpression Id. */
  int INPUT = 9;
  /** RegularExpression Id. */
  int OUTPUT = 10;
  /** RegularExpression Id. */
  int PRIMITIVE_TYPE = 11;
  /** RegularExpression Id. */
  int ARRAY = 12;
  /** RegularExpression Id. */
  int NONE = 13;
  /** RegularExpression Id. */
  int OBJECT_TYPE = 14;
  /** RegularExpression Id. */
  int PAIR = 15;
  /** RegularExpression Id. */
  int MAP = 16;
  /** RegularExpression Id. */
  int ALIAS = 17;
  /** RegularExpression Id. */
  int AS = 18;
  /** RegularExpression Id. */
  int CALL = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int TRUE_OR_FALSE = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int IN = 23;
  /** RegularExpression Id. */
  int IMPORT = 24;
  /** RegularExpression Id. */
  int LEFT = 25;
  /** RegularExpression Id. */
  int META = 26;
  /** RegularExpression Id. */
  int OBJECT = 27;
  /** RegularExpression Id. */
  int PARAMETER_META = 28;
  /** RegularExpression Id. */
  int RIGHT = 29;
  /** RegularExpression Id. */
  int RUNTIME = 30;
  /** RegularExpression Id. */
  int SCATTER = 31;
  /** RegularExpression Id. */
  int STRUCT = 32;
  /** RegularExpression Id. */
  int THEN = 33;
  /** RegularExpression Id. */
  int NULL = 34;
  /** RegularExpression Id. */
  int STANDARD_FUNCTION = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int BRAKET_L = 39;
  /** RegularExpression Id. */
  int BRAKET_R = 40;
  /** RegularExpression Id. */
  int COLON = 41;
  /** RegularExpression Id. */
  int EQUAL = 42;
  /** RegularExpression Id. */
  int PLUS = 43;
  /** RegularExpression Id. */
  int MINUS = 44;
  /** RegularExpression Id. */
  int SEMICOLON = 45;
  /** RegularExpression Id. */
  int COMMA = 46;
  /** RegularExpression Id. */
  int SUBSYMBOL = 47;
  /** RegularExpression Id. */
  int QUESTION_MARK = 48;
  /** RegularExpression Id. */
  int COMMAND = 49;
  /** RegularExpression Id. */
  int COMMAND_HEREDOC_START = 50;
  /** RegularExpression Id. */
  int COMMAND_START = 51;
  /** RegularExpression Id. */
  int START = 52;
  /** RegularExpression Id. */
  int COMMAND_END = 53;
  /** RegularExpression Id. */
  int COMMAND_HEREDOC_END = 54;
  /** RegularExpression Id. */
  int ANY = 55;
  /** RegularExpression Id. */
  int DIRECTORY = 56;
  /** RegularExpression Id. */
  int HINTS = 57;
  /** RegularExpression Id. */
  int REQUIREMENTS = 58;
  /** RegularExpression Id. */
  int TEXT_STRING = 59;
  /** RegularExpression Id. */
  int OCTAL_ESCAPE = 60;
  /** RegularExpression Id. */
  int HEX_ESCAPE = 61;
  /** RegularExpression Id. */
  int UNICODE = 62;
  /** RegularExpression Id. */
  int LETTER = 63;
  /** RegularExpression Id. */
  int DIGIT = 64;
  /** RegularExpression Id. */
  int SYMBOL = 65;
  /** RegularExpression Id. */
  int INTEGER = 66;
  /** RegularExpression Id. */
  int TRIANGULAR_BRACKET_L = 67;
  /** RegularExpression Id. */
  int TRIANGULAR_BRACKET_R = 68;
  /** RegularExpression Id. */
  int BRACE_L = 69;
  /** RegularExpression Id. */
  int BRACE_R = 70;
  /** RegularExpression Id. */
  int SQUARE_BRACKET_L = 71;
  /** RegularExpression Id. */
  int SQUARE_BRACKET_R = 72;
  /** RegularExpression Id. */
  int OPERATOR = 73;
  /** RegularExpression Id. */
  int STAR = 74;
  /** RegularExpression Id. */
  int EXPONENT = 75;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 76;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BASH_STRING = 1;
  /** Lexical state. */
  int BASH_COMMAND = 2;
  /** Lexical state. */
  int ML_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<token of kind 2>",
    "\"#\"",
    "<ML_EOL>",
    "<token of kind 5>",
    "\"task\"",
    "\"workflow\"",
    "\"version\"",
    "\"input\"",
    "\"output\"",
    "<PRIMITIVE_TYPE>",
    "\"Array\"",
    "\"None\"",
    "\"Object\"",
    "\"Pair\"",
    "\"Map\"",
    "\"alias\"",
    "\"as\"",
    "\"call\"",
    "\"else\"",
    "<TRUE_OR_FALSE>",
    "\"if\"",
    "\"in\"",
    "\"import\"",
    "\"left\"",
    "\"meta\"",
    "\"object\"",
    "\"parameter_meta\"",
    "\"right\"",
    "\"runtime\"",
    "\"scatter\"",
    "\"struct\"",
    "\"then\"",
    "\"null\"",
    "<STANDARD_FUNCTION>",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\";\"",
    "\",\"",
    "<SUBSYMBOL>",
    "\"?\"",
    "\"command\"",
    "\"<<<\"",
    "<COMMAND_START>",
    "<START>",
    "<COMMAND_END>",
    "\">>>\"",
    "<ANY>",
    "\"Directory\"",
    "\"hints\"",
    "\"requirements\"",
    "<TEXT_STRING>",
    "<OCTAL_ESCAPE>",
    "<HEX_ESCAPE>",
    "<UNICODE>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
    "<INTEGER>",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<OPERATOR>",
    "\"*\"",
    "<EXPONENT>",
    "<FLOATING_POINT_LITERAL>",
  };

}
