/* Generated By:JavaCC: Do not edit this line. WDLParserTreeConstants.java Version 7.0.10 */
package com.wdl.parser;

public interface WDLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTVERSION = 2;
  public int JJTTASK = 3;
  public int JJTREGULARFORMULAELEMENT = 4;
  public int JJTMETA = 5;
  public int JJTMETAFORMULAELEMENT = 6;
  public int JJTARRAY = 7;
  public int JJTCOMMA = 8;
  public int JJTMAP = 9;
  public int JJTKEYVALUE = 10;
  public int JJTCOLON = 11;
  public int JJTWORKFLOW = 12;
  public int JJTSCATTER = 13;
  public int JJTIN = 14;
  public int JJTCONDITIONAL = 15;
  public int JJTCOMMAND = 16;
  public int JJTBASHSTRING = 17;
  public int JJTCALL = 18;
  public int JJTSYMBOL = 19;
  public int JJTINPUT = 20;
  public int JJTEQUAL = 21;
  public int JJTRUNTIME = 22;
  public int JJTHINTS = 23;
  public int JJTOUTPUT = 24;
  public int JJTSTRUCT = 25;
  public int JJTDECLARATION = 26;
  public int JJTTYPE = 27;
  public int JJTARRAYTYPE = 28;
  public int JJTPAIRTYPE = 29;
  public int JJTMAPTYPE = 30;
  public int JJTTERNARY = 31;
  public int JJTTHEN = 32;
  public int JJTELSE = 33;
  public int JJTEXPRESSION = 34;
  public int JJTNONE = 35;
  public int JJTCONTAINERELEMENT = 36;
  public int JJTCONSTRUCTOR = 37;
  public int JJTIMPORT = 38;
  public int JJTALIAS = 39;
  public int JJTTEXT = 40;
  public int JJTFUNCTION = 41;
  public int JJTAS = 42;
  public int JJTSUBSYMBOL = 43;
  public int JJTPAIR = 44;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Version",
    "Task",
    "RegularFormulaElement",
    "Meta",
    "MetaFormulaElement",
    "Array",
    "Comma",
    "Map",
    "KeyValue",
    "Colon",
    "Workflow",
    "Scatter",
    "In",
    "Conditional",
    "Command",
    "BashString",
    "Call",
    "Symbol",
    "Input",
    "Equal",
    "Runtime",
    "Hints",
    "Output",
    "Struct",
    "Declaration",
    "Type",
    "ArrayType",
    "PairType",
    "MapType",
    "Ternary",
    "Then",
    "Else",
    "Expression",
    "None",
    "ContainerElement",
    "Constructor",
    "Import",
    "Alias",
    "Text",
    "Function",
    "As",
    "SubSymbol",
    "Pair",
  };
}
/* JavaCC - OriginalChecksum=fbc11d1e46dac0a46f55429116018948 (do not edit this line) */
